# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simulation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from s2clientprotocol import sc2api_pb2 as s2clientprotocol_dot_sc2api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='simulation.proto',
  package='SC2CombatPredictor',
  syntax='proto2',
  serialized_pb=_b('\n\x10simulation.proto\x12\x12SC2CombatPredictor\x1a\x1ds2clientprotocol/sc2api.proto\"\xe2\x01\n\x06\x42\x61ttle\x12\x13\n\x0breplay_file\x18\x01 \x01(\t\x12\x11\n\tround_num\x18\x02 \x01(\x05\x12\x38\n\x13initial_observation\x18\x03 \x01(\x0b\x32\x1b.SC2APIProtocol.Observation\x12\x33\n\x07outcome\x18\x04 \x01(\x0e\x32\".SC2CombatPredictor.Battle.Outcome\"A\n\x07Outcome\x12\x15\n\x11TEAM_MINERALS_WON\x10\x00\x12\x14\n\x10TEAM_VESPENE_WON\x10\x01\x12\t\n\x05REMIS\x10\x02\"8\n\nSimulation\x12*\n\x06\x62\x61ttle\x18\x01 \x03(\x0b\x32\x1a.SC2CombatPredictor.Battle')
  ,
  dependencies=[s2clientprotocol_dot_sc2api__pb2.DESCRIPTOR,])



_BATTLE_OUTCOME = _descriptor.EnumDescriptor(
  name='Outcome',
  full_name='SC2CombatPredictor.Battle.Outcome',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TEAM_MINERALS_WON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEAM_VESPENE_WON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REMIS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=233,
  serialized_end=298,
)
_sym_db.RegisterEnumDescriptor(_BATTLE_OUTCOME)


_BATTLE = _descriptor.Descriptor(
  name='Battle',
  full_name='SC2CombatPredictor.Battle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replay_file', full_name='SC2CombatPredictor.Battle.replay_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round_num', full_name='SC2CombatPredictor.Battle.round_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='initial_observation', full_name='SC2CombatPredictor.Battle.initial_observation', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='outcome', full_name='SC2CombatPredictor.Battle.outcome', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BATTLE_OUTCOME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=298,
)


_SIMULATION = _descriptor.Descriptor(
  name='Simulation',
  full_name='SC2CombatPredictor.Simulation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='battle', full_name='SC2CombatPredictor.Simulation.battle', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=356,
)

_BATTLE.fields_by_name['initial_observation'].message_type = s2clientprotocol_dot_sc2api__pb2._OBSERVATION
_BATTLE.fields_by_name['outcome'].enum_type = _BATTLE_OUTCOME
_BATTLE_OUTCOME.containing_type = _BATTLE
_SIMULATION.fields_by_name['battle'].message_type = _BATTLE
DESCRIPTOR.message_types_by_name['Battle'] = _BATTLE
DESCRIPTOR.message_types_by_name['Simulation'] = _SIMULATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Battle = _reflection.GeneratedProtocolMessageType('Battle', (_message.Message,), dict(
  DESCRIPTOR = _BATTLE,
  __module__ = 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:SC2CombatPredictor.Battle)
  ))
_sym_db.RegisterMessage(Battle)

Simulation = _reflection.GeneratedProtocolMessageType('Simulation', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATION,
  __module__ = 'simulation_pb2'
  # @@protoc_insertion_point(class_scope:SC2CombatPredictor.Simulation)
  ))
_sym_db.RegisterMessage(Simulation)


# @@protoc_insertion_point(module_scope)
